// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Rentals.Infrastructure;

#nullable disable

namespace Rentals.Infrastructure.Migrations
{
    [DbContext(typeof(RentalsDbContext))]
    partial class RentalsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Rentals.Domain.Drivers.DeliveryDriver", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.ToTable("user_driver", (string)null);
                });

            modelBuilder.Entity("Rentals.Domain.Users.Admin", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.ToTable("user_admin", (string)null);
                });

            modelBuilder.Entity("Rentals.Domain.Users.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long?>("AdminId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("DeliveryDriverId")
                        .HasColumnType("bigint");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("AdminId")
                        .IsUnique();

                    b.HasIndex("DeliveryDriverId")
                        .IsUnique();

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("user", (string)null);
                });

            modelBuilder.Entity("Rentals.Domain.Drivers.DeliveryDriver", b =>
                {
                    b.OwnsOne("Rentals.Domain.Drivers.Cnh", "Cnh", b1 =>
                        {
                            b1.Property<long>("DeliveryDriverId")
                                .HasColumnType("bigint");

                            b1.Property<int>("CnhCategory")
                                .HasColumnType("integer")
                                .HasColumnName("cnh_category");

                            b1.Property<string>("Number")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("cnh_number");

                            b1.HasKey("DeliveryDriverId");

                            b1.ToTable("user_driver");

                            b1.WithOwner()
                                .HasForeignKey("DeliveryDriverId");
                        });

                    b.OwnsOne("Rentals.Domain.Drivers.CnhImage", "CnhImage", b1 =>
                        {
                            b1.Property<long>("DeliveryDriverId")
                                .HasColumnType("bigint");

                            b1.Property<string>("BlobPath")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("cnh_image_file");

                            b1.Property<string>("ContentType")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("cnh_image_type");

                            b1.HasKey("DeliveryDriverId");

                            b1.ToTable("user_driver");

                            b1.WithOwner()
                                .HasForeignKey("DeliveryDriverId");
                        });

                    b.OwnsOne("Rentals.Domain.Drivers.Cnpj", "Cnpj", b1 =>
                        {
                            b1.Property<long>("DeliveryDriverId")
                                .HasColumnType("bigint");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(14)
                                .HasColumnType("character varying(14)")
                                .HasColumnName("cnpj");

                            b1.HasKey("DeliveryDriverId");

                            b1.ToTable("user_driver");

                            b1.WithOwner()
                                .HasForeignKey("DeliveryDriverId");
                        });

                    b.Navigation("Cnh")
                        .IsRequired();

                    b.Navigation("CnhImage");

                    b.Navigation("Cnpj")
                        .IsRequired();
                });

            modelBuilder.Entity("Rentals.Domain.Users.User", b =>
                {
                    b.HasOne("Rentals.Domain.Users.Admin", "Admin")
                        .WithOne()
                        .HasForeignKey("Rentals.Domain.Users.User", "AdminId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Rentals.Domain.Drivers.DeliveryDriver", "DeliveryDriver")
                        .WithOne()
                        .HasForeignKey("Rentals.Domain.Users.User", "DeliveryDriverId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Admin");

                    b.Navigation("DeliveryDriver");
                });
#pragma warning restore 612, 618
        }
    }
}
